### ISSUE TITLE
requiring python>=3.9 is too restrictive

### ISSUE THREAD

**Issue by suvarchal** [siligam/sworkflow#1]
not sure why python>=3.9 is needed specifically (just graphlib?). Given the tool is meant to be used in HPC it does make sense, if possible, to allow python>3.6 (might be worth effort).

**Comment by siligam** [comment]
Apparently there is back port of graphlib to support python>3.6

Setting the following in requirements.txt should do

`graphlib_backport; python_version < "3.9.0"`

As of now, 3.6 and 3.7 reached end of life, i wonder if it still make sense to apply this change

**Comment by siligam** [comment]
add this change to requirements.txt file
